export const CONSUME_SLOTS = 'CONSUME_SLOTS';
export const SELECT_SLOT = 'SELECT_SLOT';
export const DESELECT_SLOT = 'DESELECT_SLOT';

export const CHANGE_BET_AMOUNT = 'CHANGE_BET_AMOUNT';

export const NAX_SLOTS_CLICKED = 12;